language: python
python:
    - "3.6"
jobs:
  include:

    - stage: test
      install:
          - pip install -r requirements_test.txt
      script: py.test
    - stage: release
      deploy:
          provider: script
          skip_cleanup: true
          install:
          script:
              - nvm install lts/*
              - npx semantic-release
