language: python
python:
    - "3.6"
jobs:
  include:

    - stage: test
      install:
          - pip install -r requirements_test.txt
      script: py.test
    - stage: release
      before_install:
          - nvm install lts/*
      install:
          - pip install -r requirements_ci.txt
          - npm install
      script: skip
      deploy:
          provider: script
          skip_cleanup: true
          script:
              - npx semantic-release
